### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by bvanrijn** [bvanrijn/debianpaste-clients#4]
**Note:** This obsoletes the [TODO](https://github.com/bvanrijn/debianpaste-clients/blob/master/TODO) file. Any new TODOs must be written here as comments.
- [ ] paste web-view url into x-buffer
- [ ] automatic file detection from file extension
- [ ] paste file without cat
- [ ] 'add' per default without explicitly specifying

**Comment by bvanrijn** [comment]
- [x] find a more concise way (with the script) to handle the actionGetShortUrl exception (#2)
